### ISSUE TITLE
Is this updated Adobe XD Kit?

### ISSUE THREAD

**Issue by devi7911** [IBM/design-kit#18]
## Detailed description

I see there are few changes to the UI Kit when compared with React and Angular demo version.

> Which version of the kit are you using?
Carbon Design System - V10 - White (11.01.19)

> Is this a bug or feature enhancement request?
It's a request about if the version that is available on the site is updated version or not.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Components: Dropdown (White theme). I was looking for various components, but the one I'm currently looking for is this. If the kit is updated, then it should look like the one I saw in the live demo version. Or the demo version is not updated? I'm not sure about it.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Yes, I see there is a difference between the live version and kit version, but I'm not sure which one is the latest version and which one is not.

## Additional information
As you can see the below screenshots, there are no combo box, filterable multiselect and there are also slight changes to the UI too. Can you please let me know if there is an updated version of Adobe XD kit or I need to use this one only?

* Screenshots or Sketch file links
* Notes
![2021-04-07 (5)](https://user-images.githubusercontent.com/60746128/113807378-a503d800-9781-11eb-8e12-5f8f9dff4f8c.png)
![2021-04-07 (6)](https://user-images.githubusercontent.com/60746128/113807389-a7663200-9781-11eb-8ec0-bcec37b7f747.png)
![2021-04-07 (7)](https://user-images.githubusercontent.com/60746128/113807391-a8975f00-9781-11eb-9780-ce815bde3c11.png)

**Comment by laurenmrice** [comment]
An update is coming soon for the Adobe XD kits that will include these component variants. We will have a kit per theme that will include all of our components. The kits will also be connected to Adobes Cloud, and we will update our website to make them available to you.

**Comment by devi7911** [comment]
Thank you very much for the update. Looking forward to it.
