### ISSUE TITLE
How can I get the license as an IBMer to use Adobe XD?

### ISSUE THREAD

**Issue by paulamorell** [IBM/design-kit#27]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> Which version of the kit are you using?

> Is this a bug or feature enhancement request?

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

> If a bug, what did you expect to happen? What happened instead? What would you like to see changed?

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

## Additional information

* Screenshots or Sketch file links
* Notes

**Comment by laurenmrice** [comment]
@paulamorell I’d reach out to your Adobe Admin at IBM to get access to a IBM license for Adobe XD.

**Richard (Rick) N. Smith**
Devices @ IBM Software License Management Service Owner
Enterprise Services
Phone: [+1.203.486.4877](tel:+12034864877)
Email: [rnsmith@us.ibm.com](mailto:rnsmith@us.ibm.com)
