### ISSUE TITLE
Carbon adobe kit - attempting to download throws 404

### ISSUE THREAD

**Issue by camilascalzo** [IBM/design-kit#30]
## Detailed description

attempting to download  XD kit throws 404
https://www.carbondesignsystem.com/designing/kits/adobe-xd/#get-the-kit 

https://github.com/IBM/design-kit/raw/master/Adobe%20XD/Carbon%20Design%20System%20-%20V10%20-%20White%20(11.01.19).xd

**Comment by aagonzales** [comment]
@camilascalzo We've got an update coming out later today for this, we're launching a new way to get the XD kits. It will be up on the s[ame website link](https://www.carbondesignsystem.com/designing/kits/adobe-xd/#get-the-kit).

**Comment by camilascalzo** [comment]
@aagonzales Thank you!!

**Comment by aagonzales** [comment]
FYI You can also Download them from this repo directly: https://github.com/IBM/design-kit/tree/master/Adobe%20XD
