### ISSUE TITLE
Asking about ADOBEXD kit - carbondesignsystem.com

### ISSUE THREAD

**Issue by MrajcaM** [IBM/design-kit#32]
Hello,

I would like to ask about opportunity to get ADOBE XD kit (carbondesignsystem.com)

I would be grateful for considering my request.

Greetings,
Malgorzata

**Comment by laurenmrice** [comment]
@MrajcaM You can download the available Carbon Adobe XD kits here. https://github.com/IBM/design-kit/tree/master/Adobe%20XD

The White, Gray 10, Gray 90, and Gray 100 themes are available to download as well as an IBM Icon kit.

**Comment by MrajcaM** [comment]
@laurenmrice thank you!
