### ISSUE TITLE
Design kit access

### ISSUE THREAD

**Issue by licharbono** [IBM/design-kit#35]
Hi guys! Do we need to request access to the design kit? I can't find through the CC app, and get an 'asset not found' error message when trying to view online. Thanks!

**Comment by laurenmrice** [comment]
@licharbono Our CC libraries are only available to IBMers. Eventually we hope to make them available to the public community. Instead you can download them here https://github.com/IBM/design-kit/tree/master/Adobe%20XD

**Comment by licharbono** [comment]
Thank you so much, Lauren! Much appreciated.
