### ISSUE TITLE
Naming convention of layer styles in sketch libraries

### ISSUE THREAD

**Issue by josh-tt** [IBM/design-kit#5]
The v2 and V1 sketch styles are named with no spaces between the classes. 

@aagonzales  I understand that the / is for the tree structure, but some of the IBM libraries have a space (for example, Carbon themes) and the others don't.   It's a minor inconsistency between the documents and how the styles were created/named, but an inconsistency nonetheless that was worth mentioning as it requires writing the classes differently if using a plugin to update layer styles via scss.

**Carbon style names (have a space)**
state / active-danger

vs

**V1/V2 Language file style naming (have no space)**
color/gray/10

**Comment by aagonzales** [comment]
Yup, we made the decision to include spaces to help with legibility in the file. We'll need to update Language libraries to include this. @laurenmrice @joshblack

**Comment by laurenmrice** [comment]
Yeah looks like the colors do not have the space  in the v2 kit. We will update that

**Comment by laurenmrice** [comment]
fixed ! will be in next update 🙌🏻
